// calcs.js — Interactive numeric calculation drills (preserved & extended from
// the original CDD app, plus the calculations embedded in the 2023/2024 papers).
//
// Shape: { id, topic, lecture, source, type:"calc", marks, stem, formula,
//          steps:[...], answer:<number>, unit, tolerance, feedback:{...} }
// The grader checks the numeric answer within tolerance AND that units were
// stated (units are required for full marks in this module).

const CALC_BANK = [
  {
    id: "calc-hl-1", topic: "B5 · Pharmacokinetics", lecture: "L11", source: "core",
    type: "calc", marks: 2,
    stem: "A drug has Vd = 50 L and total clearance CL = 10 L/h. Calculate the elimination half-life.",
    formula: "t½ = 0.693 × Vd / CL",
    steps: ["Identify: Vd = 50 L; CL = 10 L/h.", "t½ = 0.693 × 50 / 10", "t½ = 3.465 h ≈ 3.5 h (1 d.p.)"],
    answer: 3.47, unit: "h", tolerance: 0.1,
    feedback: { unit: "Always state units (hours).", rounding: "Don't round prematurely — carry digits to the final step.", conceptual: "t½ depends on BOTH Vd and CL; a bigger Vd lengthens t½." },
  },
  {
    id: "calc-hl-2", topic: "B5 · Pharmacokinetics", lecture: "L11", source: "core",
    type: "calc", marks: 3,
    stem: "After an IV bolus of 200 mg, plasma concentration is 4 mg/L at t = 0 (extrapolated) and falls to 1 mg/L at t = 6 h (first-order). Calculate the half-life.",
    formula: "C(t) = C0·e^(−kt);  t½ = ln2 / k",
    steps: ["C/C0 = 1/4 = e^(−k·6) → ln(0.25) = −6k → k = ln4 / 6 ≈ 0.231 h⁻¹.", "t½ = 0.693 / 0.231 ≈ 3 h.", "Check: 4 → 2 → 1 mg/L is two half-lives over 6 h, so t½ = 3 h."],
    answer: 3.0, unit: "h", tolerance: 0.2,
    feedback: { arithmetic: "Going 4 → 1 is two halvings, so each half-life is 3 h — verify by inspection.", conceptual: "Linearise log(C) vs t to read off k directly." },
  },
  {
    id: "calc-cl-1", topic: "B5 · Pharmacokinetics", lecture: "L11", source: "core",
    type: "calc", marks: 3,
    stem: "At steady state, an IV infusion of 5 mg/h gives a plasma concentration of 2 mg/L. Calculate total body clearance.",
    formula: "CL = dose rate / Css",
    steps: ["CL = (5 mg/h) / (2 mg/L)", "CL = 2.5 L/h", "= 2500 mL/h ÷ 60 ≈ 41.7 mL/min."],
    answer: 2.5, unit: "L/h", tolerance: 0.05,
    feedback: { conceptual: "At steady state input = output: dose rate = CL × Css.", unit: "State L/h (or mL/min)." },
  },
  {
    id: "calc-cl-2", topic: "B5 · Pharmacokinetics", lecture: "L11", source: "2024",
    type: "calc", marks: 4,
    stem: "A candidate drug has an oral half-life t½ = 15 h and a volume of distribution Vd = 37.4 L. Calculate the clearance. (2024 Case Study 1, Q5B)",
    formula: "CL = 0.693 × Vd / t½",
    steps: ["Rearrange t½ = 0.693 × Vd / CL → CL = 0.693 × Vd / t½.", "CL = 0.693 × 37.4 / 15.", "CL = 25.9 / 15 ≈ 1.73 L/h (≈ 28.8 mL/min)."],
    answer: 1.73, unit: "L/h", tolerance: 0.1,
    feedback: { unit: "State L/h (or mL/min).", arithmetic: "CL = 0.693 × 37.4 = 25.9, then ÷ 15 = 1.73.", conceptual: "Clearance falls out of the half-life equation once Vd and t½ are known." },
  },
  {
    id: "calc-f-1", topic: "B5 · Pharmacokinetics", lecture: "L10", source: "core",
    type: "calc", marks: 2,
    stem: "AUC after a 100 mg oral dose is 30 mg·h/L; AUC after the same 100 mg IV dose is 75 mg·h/L. Calculate oral bioavailability F.",
    formula: "F = AUC(oral) / AUC(IV)  (same dose)",
    steps: ["Same dose by both routes.", "F = 30 / 75 = 0.4 = 40%."],
    answer: 0.4, unit: "(40%)", tolerance: 0.02,
    feedback: { conceptual: "F = 1 for IV; oral F < 1 from incomplete absorption + first-pass metabolism.", arithmetic: "Route on top, IV on the bottom — don't invert." },
  },
  {
    id: "calc-vd-1", topic: "B5 · Pharmacokinetics", lecture: "L10", source: "core",
    type: "calc", marks: 2,
    stem: "A 700 mg IV bolus produces a plasma concentration of 10 mg/L immediately after distribution. Calculate the apparent volume of distribution.",
    formula: "Vd = Q / Cp",
    steps: ["Vd = 700 mg / 10 mg/L = 70 L.", "70 L > total body water (~42 L) → tissue distribution."],
    answer: 70, unit: "L", tolerance: 0.5,
    feedback: { conceptual: "Vd is not a real anatomical volume — a large Vd implies tissue partitioning.", unit: "State L." },
  },
  {
    id: "calc-vd-2", topic: "B5 · Pharmacokinetics", lecture: "L10", source: "2024",
    type: "calc", marks: 2,
    stem: "Calculate the apparent volume of distribution for Drug A: total drug in body Q = 4 mg, plasma concentration Cp = 0.03 mg/L. (2024 Section A, Q5; the other drugs are B 40 mg/1.6, C 20 mg/0.3, D 15 mg/0.04.)",
    formula: "Vd = Q / Cp",
    steps: ["Vd(A) = 4 / 0.03 = 133 L.", "(For reference: B = 40/1.6 = 25 L; C = 20/0.3 = 67 L; D = 15/0.04 = 375 L.)", "Largest Vd (Drug D) → most tissue-bound → highest log P."],
    answer: 133, unit: "L", tolerance: 3,
    feedback: { unit: "State L.", conceptual: "The drug with the largest Vd (D) is the most lipophilic, so has the highest log P.", arithmetic: "Vd = amount ÷ concentration; keep the units consistent (mg ÷ mg/L = L)." },
  },
  {
    id: "calc-dose-rat", topic: "B6 · Preclinical & Safety", lecture: "L13", source: "2023",
    type: "calc", marks: 3,
    stem: "ManUPharm1 is dosed at 8 mg/kg. What dose should be administered to a 280 g rat? Show your working. (2023 Case Study 2, Q1)",
    formula: "Dose = dose per kg × body weight (in kg)",
    steps: ["Convert weight: 280 g = 0.28 kg.", "Dose = 8 mg/kg × 0.28 kg.", "Dose = 2.24 mg."],
    answer: 2.24, unit: "mg", tolerance: 0.05,
    feedback: { unit: "State mg.", arithmetic: "Convert grams to kilograms FIRST (280 g = 0.28 kg), then multiply.", conceptual: "Per-weight dosing scales the dose to body mass." },
  },
  {
    id: "calc-basolateral", topic: "B5 · Pharmacokinetics", lecture: "L10", source: "2024",
    type: "calc", marks: 2,
    stem: "In a Caco-2 assay, 50 µM of drug was added to the apical side. At 24 h the basolateral concentration of ManUPharm1 is 29.6 µM. Calculate the % of drug that has entered the basolateral compartment. (2024 Case Study 2, Q4)",
    formula: "% basolateral = (basolateral conc / initial apical conc) × 100",
    steps: ["% = (29.6 / 50) × 100.", "% = 59.2%."],
    answer: 59.2, unit: "%", tolerance: 1,
    feedback: { unit: "State %.", arithmetic: "Divide the basolateral concentration by the 50 µM starting concentration, then ×100.", conceptual: "This fraction crossing the monolayer is a measure of apparent permeability/absorption." },
  },
  {
    id: "calc-ec50-1", topic: "B2 · Mechanisms of Drug Action", lecture: "L03", source: "core",
    type: "calc", marks: 2,
    stem: "A concentration–response curve gives a pEC50 of 7.5 for a full agonist (concentration in M). Calculate the EC50 in nM.",
    formula: "EC50 = 10^(−pEC50)",
    steps: ["EC50 (M) = 10^(−7.5) = 3.16 × 10⁻⁸ M.", "× 10⁹ nM/M = 31.6 nM."],
    answer: 31.6, unit: "nM", tolerance: 1.5,
    feedback: { unit: "Always state units — quoting only pEC50 loses marks.", arithmetic: "10^(−7.5) ≈ 3.16 × 10⁻⁸, not 1 × 10⁻⁸." },
  },
  {
    id: "calc-ec50-2", topic: "B2 · Mechanisms of Drug Action", lecture: "L03", source: "core",
    type: "calc", marks: 3,
    stem: "From a sigmoidal log[A] vs response curve, the maximal response is 100 units and the response is 50 units at log[A] = −7 (A in M). Express the EC50 with units.",
    formula: "At 50% Emax, x = log(EC50); EC50 = 10^(log)",
    steps: ["50 units = 50% of Emax, so log[A] at 50% = −7.", "EC50 = 10^(−7) M = 1 × 10⁻⁷ M = 100 nM."],
    answer: 100, unit: "nM", tolerance: 5,
    feedback: { unit: "Must include units (M/nM). 'log EC50' alone earns only half marks.", conceptual: "EC50 is the log[A] where the curve crosses 50% of Emax." },
  },
  {
    id: "calc-ti-1", topic: "B6 · Preclinical & Safety", lecture: "L14", source: "core",
    type: "calc", marks: 2,
    stem: "Drug X has LD50 = 800 mg/kg and ED50 = 20 mg/kg. Calculate the therapeutic index.",
    formula: "TI = LD50 / ED50",
    steps: ["TI = 800 / 20 = 40.", "(Dimensionless ratio.)"],
    answer: 40, unit: "(dimensionless)", tolerance: 0.5,
    feedback: { conceptual: "TI is dimensionless; a high TI doesn't guarantee safety (curve slopes, idiosyncratic ADRs).", arithmetic: "Large LD50 / small ED50 = wider safety window." },
  },
  {
    id: "calc-shift-1", topic: "B2 · Mechanisms of Drug Action", lecture: "L03", source: "core",
    type: "calc", marks: 3,
    stem: "A full agonist has EC50 = 50 nM. With a competitive antagonist present, the curve shifts in parallel to the right with a new EC50 = 800 nM. Calculate the dose ratio (DR).",
    formula: "DR = EC50(+antagonist) / EC50(control)",
    steps: ["DR = 800 / 50 = 16.", "Parallel right shift with unchanged Emax = competitive (surmountable) antagonism."],
    answer: 16, unit: "(dose ratio)", tolerance: 0.5,
    feedback: { conceptual: "Parallel right shift + unchanged Emax = competitive; an Emax fall = non-competitive.", arithmetic: "DR is dimensionless; both EC50s must share units." },
  },
  {
    id: "calc-dose-1", topic: "B5 · Pharmacokinetics", lecture: "L10", source: "core",
    type: "calc", marks: 2,
    stem: "A drug must reach Cmax of 1.5 mg/L. Vd = 40 L and oral bioavailability F = 0.5. Calculate the required oral dose.",
    formula: "Dose = (Cmax × Vd) / F",
    steps: ["Body burden Q = Cmax × Vd = 1.5 × 40 = 60 mg.", "Oral dose = Q / F = 60 / 0.5 = 120 mg."],
    answer: 120, unit: "mg", tolerance: 1,
    feedback: { conceptual: "Lower F needs a higher oral dose for the same Cp.", unit: "State mg." },
  },
  {
    id: "calc-dose-2", topic: "B5 · Pharmacokinetics", lecture: "L11", source: "core",
    type: "calc", marks: 4,
    stem: "For a drug with Vd = 40 L, CL = 5 L/h and F = 0.7: calculate (a) the IV loading dose to reach Cp = 2 mg/L and (b) the oral maintenance dose every 8 h (steady state). Give the maintenance dose.",
    formula: "Loading: Q = Cp × Vd.  Maintenance: oral dose × F / τ = CL × Css",
    steps: ["Loading IV: Q = 2 × 40 = 80 mg.", "Maintenance rate = CL × Css = 5 × 2 = 10 mg/h.", "Over τ = 8 h: oral dose × 0.7 = 10 × 8 = 80 → oral dose = 80 / 0.7 ≈ 114 mg every 8 h."],
    answer: 114, unit: "mg every 8 h", tolerance: 5,
    feedback: { conceptual: "Loading sets the body burden (Vd); maintenance balances clearance.", arithmetic: "Divide by F for oral dosing — incomplete bioavailability needs a larger dose." },
  },

  // =====================================================================
  // EXTENDED CALCULATION BANK — worked steps included in the feedback
  // =====================================================================
  {
    id: "calc-hl-frac", topic: "B5 · Pharmacokinetics", lecture: "L11", source: "core",
    type: "calc", marks: 2,
    stem: "A drug has a half-life of 4 h and is eliminated by first-order kinetics. What percentage of an IV dose remains in the body 12 hours after administration?",
    formula: "fraction remaining = (½)^n, where n = time ÷ t½",
    steps: ["Number of half-lives: n = 12 h ÷ 4 h = 3.", "Fraction remaining = (½)³ = 1/8 = 0.125.", "× 100 = 12.5%."],
    answer: 12.5, unit: "%", tolerance: 0.3,
    feedback: {
      conceptual: "First-order elimination removes a constant FRACTION per half-life, so after each t½ the amount halves: 100% → 50% → 25% → 12.5%.",
      arithmetic: "Step 1: n = time/t½ = 12/4 = 3 half-lives. Step 2: each half-life multiplies by ½, so after 3 it is (½)^3 = 1/8. Step 3: 1/8 = 0.125 = 12.5%.",
      unit: "Answer is a percentage (%) — don't forget the % sign.",
    },
  },
  {
    id: "calc-ss-time", topic: "B5 · Pharmacokinetics", lecture: "L11", source: "core",
    type: "calc", marks: 2,
    stem: "A drug given by constant IV infusion has a half-life of 8 h. Approximately how long will it take to reach steady state? (Take steady state as ~5 half-lives.)",
    formula: "time to steady state ≈ 5 × t½",
    steps: ["Steady state is reached after about 5 half-lives.", "Time ≈ 5 × 8 h = 40 h."],
    answer: 40, unit: "h", tolerance: 1,
    feedback: {
      conceptual: "On a constant infusion, plasma concentration climbs toward Css; after 1 t½ you are ~50% of the way, after 5 t½ you are ~97% there — taken as 'steady state'. This depends only on t½, not on the infusion rate.",
      arithmetic: "Step 1: rule of thumb = 5 half-lives. Step 2: 5 × 8 h = 40 h.",
      unit: "State the answer in hours (h).",
    },
  },
  {
    id: "calc-cl-auc", topic: "B5 · Pharmacokinetics", lecture: "L11", source: "core",
    type: "calc", marks: 2,
    stem: "After a 100 mg IV bolus, the area under the plasma concentration–time curve (AUC) is 20 mg·h/L. Calculate the total body clearance.",
    formula: "CL = Dose / AUC  (for IV)",
    steps: ["CL = Dose ÷ AUC = 100 mg ÷ 20 mg·h/L.", "CL = 5 L/h."],
    answer: 5, unit: "L/h", tolerance: 0.1,
    feedback: {
      conceptual: "Clearance is the volume of plasma cleared of drug per unit time; for an IV dose it equals Dose/AUC. (For an oral dose you would multiply by F: CL = F·Dose/AUC.)",
      arithmetic: "Step 1: CL = Dose/AUC. Step 2: 100 mg ÷ 20 mg·h/L = 5. The mg cancels, leaving L/h.",
      unit: "Units are L/h (check by cancelling: mg ÷ (mg·h/L) = L/h).",
    },
  },
  {
    id: "calc-load-iv", topic: "B5 · Pharmacokinetics", lecture: "L10", source: "core",
    type: "calc", marks: 2,
    stem: "Calculate the IV loading dose needed to achieve a target plasma concentration of 5 mg/L in a patient whose volume of distribution is 35 L.",
    formula: "Loading dose = Cp(target) × Vd",
    steps: ["Loading dose = target Cp × Vd = 5 mg/L × 35 L.", "= 175 mg."],
    answer: 175, unit: "mg", tolerance: 2,
    feedback: {
      conceptual: "A loading dose fills the volume of distribution to reach the target concentration immediately; it depends on Vd (not clearance). Maintenance dosing then balances clearance.",
      arithmetic: "Step 1: Loading dose = Cp × Vd. Step 2: 5 mg/L × 35 L = 175 mg (the L cancels).",
      unit: "State mg.",
    },
  },
  {
    id: "calc-load-oral", topic: "B5 · Pharmacokinetics", lecture: "L10", source: "core",
    type: "calc", marks: 3,
    stem: "A drug has Vd = 50 L and oral bioavailability F = 0.8. Calculate the ORAL loading dose required to reach a plasma concentration of 4 mg/L.",
    formula: "Oral loading dose = (Cp × Vd) / F",
    steps: ["Body amount needed: Q = Cp × Vd = 4 mg/L × 50 L = 200 mg.", "Correct for bioavailability: oral dose = Q / F = 200 / 0.8.", "= 250 mg."],
    answer: 250, unit: "mg", tolerance: 3,
    feedback: {
      conceptual: "Only a fraction F of an oral dose reaches the circulation, so the oral dose must be LARGER than the equivalent IV dose. Lower F → bigger oral dose.",
      arithmetic: "Step 1: amount needed in body Q = Cp × Vd = 4 × 50 = 200 mg. Step 2: divide by F because only 80% is absorbed: 200 ÷ 0.8 = 250 mg.",
      unit: "State mg.",
    },
  },
  {
    id: "calc-infusion-rate", topic: "B5 · Pharmacokinetics", lecture: "L11", source: "core",
    type: "calc", marks: 2,
    stem: "A drug has a clearance of 3 L/h. Calculate the constant IV infusion rate needed to maintain a steady-state plasma concentration of 10 mg/L.",
    formula: "Infusion rate = CL × Css",
    steps: ["At steady state, rate in = rate out = CL × Css.", "Rate = 3 L/h × 10 mg/L = 30 mg/h."],
    answer: 30, unit: "mg/h", tolerance: 0.5,
    feedback: {
      conceptual: "At steady state, the rate of drug going in equals the rate being cleared (CL × Css). This sets the maintenance dose rate and depends on clearance, not Vd.",
      arithmetic: "Step 1: rate = CL × Css. Step 2: 3 L/h × 10 mg/L = 30 mg/h (the L cancels).",
      unit: "Units are mg/h (a rate).",
    },
  },
  {
    id: "calc-f-dose", topic: "B5 · Pharmacokinetics", lecture: "L10", source: "core",
    type: "calc", marks: 3,
    stem: "Oral dosing of 200 mg gives an AUC of 24 mg·h/L; IV dosing of 100 mg gives an AUC of 30 mg·h/L. Calculate the absolute oral bioavailability, F.",
    formula: "F = (AUC_oral × Dose_IV) / (AUC_IV × Dose_oral)",
    steps: ["Because the doses differ, correct for dose: F = (AUC_oral × Dose_IV) / (AUC_IV × Dose_oral).", "F = (24 × 100) / (30 × 200) = 2400 / 6000.", "F = 0.4 = 40%."],
    answer: 0.4, unit: "(40%)", tolerance: 0.02,
    feedback: {
      conceptual: "Bioavailability compares systemic exposure (AUC) by the test route with IV (F = 1). When the oral and IV doses are NOT equal you must normalise to dose.",
      arithmetic: "Step 1: F = (AUC_oral × Dose_IV)/(AUC_IV × Dose_oral). Step 2: numerator = 24 × 100 = 2400; denominator = 30 × 200 = 6000. Step 3: 2400/6000 = 0.40 = 40%.",
      unit: "F is a fraction (or %). A common error is forgetting the dose correction when doses differ.",
    },
  },
  {
    id: "calc-vd-weight", topic: "B5 · Pharmacokinetics", lecture: "L10", source: "core",
    type: "calc", marks: 3,
    stem: "A 70 kg patient is given a 350 mg IV bolus of a drug whose volume of distribution is 0.5 L/kg. Calculate the expected initial plasma concentration.",
    formula: "Vd(L) = Vd/kg × weight;  Cp = Dose / Vd",
    steps: ["Total Vd = 0.5 L/kg × 70 kg = 35 L.", "Cp = Dose / Vd = 350 mg / 35 L.", "Cp = 10 mg/L."],
    answer: 10, unit: "mg/L", tolerance: 0.3,
    feedback: {
      conceptual: "Vd is often quoted per kg of body weight; multiply by weight to get the patient's Vd, then Cp = Dose/Vd (rearranged from Vd = Q/Cp).",
      arithmetic: "Step 1: Vd = 0.5 L/kg × 70 kg = 35 L. Step 2: Cp = 350 mg ÷ 35 L = 10 mg/L.",
      unit: "State mg/L. Watch the per-kg step — forgetting to multiply by body weight is the usual error.",
    },
  },
  {
    id: "calc-dose-rat2", topic: "B6 · Preclinical & Safety", lecture: "L13", source: "core",
    type: "calc", marks: 2,
    stem: "A candidate drug is dosed at 5 mg/kg. What dose should be administered to a 350 g rat? Show your working.",
    formula: "Dose = dose per kg × body weight (in kg)",
    steps: ["Convert weight: 350 g = 0.35 kg.", "Dose = 5 mg/kg × 0.35 kg.", "Dose = 1.75 mg."],
    answer: 1.75, unit: "mg", tolerance: 0.05,
    feedback: {
      conceptual: "Per-weight dosing scales the dose to body mass — exactly the 2023 'dose to a 280 g rat' calculation with different numbers.",
      arithmetic: "Step 1: convert grams to kilograms FIRST: 350 g ÷ 1000 = 0.35 kg. Step 2: multiply: 5 mg/kg × 0.35 kg = 1.75 mg.",
      unit: "State mg. The classic mistake is forgetting to convert g → kg (which would give a 1000× error).",
    },
  },
  {
    id: "calc-basolateral2", topic: "B5 · Pharmacokinetics", lecture: "L10", source: "core",
    type: "calc", marks: 2,
    stem: "In a Caco-2 assay, 50 µM of a drug is added to the apical side. At 8 h the basolateral concentration is 41.6 µM. Calculate the % of drug that has entered the basolateral compartment.",
    formula: "% basolateral = (basolateral conc / initial apical conc) × 100",
    steps: ["% = (41.6 / 50) × 100.", "% = 83.2%."],
    answer: 83.2, unit: "%", tolerance: 1,
    feedback: {
      conceptual: "This is the 2024 case-study calculation (same method, different time point): the fraction crossing the monolayer is a measure of apparent permeability/absorption.",
      arithmetic: "Step 1: divide the basolateral concentration by the 50 µM starting concentration: 41.6 ÷ 50 = 0.832. Step 2: × 100 = 83.2%.",
      unit: "State %. Always divide by the INITIAL apical concentration (50 µM), not the current apical value.",
    },
  },
  {
    id: "calc-ti-2", topic: "B6 · Preclinical & Safety", lecture: "L14", source: "core",
    type: "calc", marks: 2,
    stem: "A drug has a maximum non-toxic dose (TD50) of 500 mg/kg and a minimum effective dose (ED50) of 25 mg/kg. Calculate the therapeutic index.",
    formula: "TI = TD50 (or LD50) / ED50",
    steps: ["TI = 500 / 25.", "TI = 20 (dimensionless)."],
    answer: 20, unit: "(dimensionless)", tolerance: 0.5,
    feedback: {
      conceptual: "TI is the ratio of the toxic dose to the effective dose — a larger TI implies a wider safety margin, but it ignores curve slopes and idiosyncratic reactions (e.g. thalidomide has a high TI yet is dangerous).",
      arithmetic: "Step 1: TI = TD50/ED50. Step 2: 500 ÷ 25 = 20. The mg/kg units cancel, so TI is dimensionless.",
      unit: "TI has no units (it's a ratio of two doses).",
    },
  },
  {
    id: "calc-cl-hl2", topic: "B5 · Pharmacokinetics", lecture: "L11", source: "core",
    type: "calc", marks: 3,
    stem: "A drug has a half-life of 10 h and a volume of distribution of 28 L. Calculate its clearance.",
    formula: "CL = 0.693 × Vd / t½",
    steps: ["Rearrange t½ = 0.693 × Vd / CL → CL = 0.693 × Vd / t½.", "CL = 0.693 × 28 / 10 = 19.4 / 10.", "CL = 1.94 L/h."],
    answer: 1.94, unit: "L/h", tolerance: 0.1,
    feedback: {
      conceptual: "Same relationship as the 2024 case study (t½, Vd → CL). Clearance rises with a shorter half-life and a larger Vd.",
      arithmetic: "Step 1: CL = 0.693 × Vd / t½. Step 2: 0.693 × 28 = 19.4. Step 3: 19.4 ÷ 10 = 1.94 L/h.",
      unit: "State L/h. Keep 0.693 (= ln2) in the equation — leaving it out is a common slip.",
    },
  },
  {
    id: "calc-k-from-hl", topic: "B5 · Pharmacokinetics", lecture: "L11", source: "core",
    type: "calc", marks: 2,
    stem: "A drug is eliminated by first-order kinetics with a half-life of 3 h. Calculate the elimination rate constant, k.",
    formula: "k = 0.693 / t½",
    steps: ["k = 0.693 / 3.", "k = 0.231 h⁻¹."],
    answer: 0.231, unit: "h⁻¹", tolerance: 0.005,
    feedback: {
      conceptual: "k is the fraction of drug eliminated per unit time. For first-order kinetics k and t½ are linked by k = ln2/t½ (ln2 = 0.693).",
      arithmetic: "Step 1: k = 0.693/t½. Step 2: 0.693 ÷ 3 = 0.231 per hour.",
      unit: "Units are h⁻¹ (per hour) — a rate constant, not a time.",
    },
  },
  {
    id: "calc-hl-from-k", topic: "B5 · Pharmacokinetics", lecture: "L11", source: "core",
    type: "calc", marks: 2,
    stem: "A drug has a first-order elimination rate constant k = 0.10 h⁻¹. Calculate its half-life.",
    formula: "t½ = 0.693 / k",
    steps: ["t½ = 0.693 / 0.10.", "t½ = 6.93 h."],
    answer: 6.93, unit: "h", tolerance: 0.1,
    feedback: {
      conceptual: "This is the reverse of finding k from t½: t½ = ln2/k. A smaller k (slower elimination) gives a longer half-life.",
      arithmetic: "Step 1: t½ = 0.693/k. Step 2: 0.693 ÷ 0.10 = 6.93 h.",
      unit: "State hours (h).",
    },
  },
  {
    id: "calc-pec50-2", topic: "B2 · Mechanisms of Drug Action", lecture: "L03", source: "core",
    type: "calc", marks: 2,
    stem: "An agonist has a pEC50 of 8.2 (concentration in M). Express the EC50 in nM.",
    formula: "EC50 (M) = 10^(−pEC50);  × 10⁹ to convert to nM",
    steps: ["EC50 = 10^(−8.2) M = 6.31 × 10⁻⁹ M.", "× 10⁹ nM/M = 6.31 nM."],
    answer: 6.31, unit: "nM", tolerance: 0.4,
    feedback: {
      conceptual: "pEC50 = −log10(EC50 in M), so a higher pEC50 means a lower EC50 and a MORE potent agonist.",
      arithmetic: "Step 1: EC50 = 10^(−8.2). Split as 10^(−9) × 10^(0.8); 10^(0.8) ≈ 6.31, so EC50 = 6.31 × 10⁻⁹ M. Step 2: 1 M = 10⁹ nM, so 6.31 × 10⁻⁹ M = 6.31 nM.",
      unit: "Always quote units — '6.31' alone is meaningless; here it is nM.",
    },
  },
  {
    id: "calc-css-infusion", topic: "B5 · Pharmacokinetics", lecture: "L11", source: "core",
    type: "calc", marks: 2,
    stem: "A drug is given by constant IV infusion at 12 mg/h. Its clearance is 4 L/h. Calculate the steady-state plasma concentration.",
    formula: "Css = infusion rate / CL",
    steps: ["Css = rate / CL = 12 mg/h ÷ 4 L/h.", "Css = 3 mg/L."],
    answer: 3, unit: "mg/L", tolerance: 0.1,
    feedback: {
      conceptual: "Rearranges 'infusion rate = CL × Css'. Steady-state concentration is set by the balance of input (infusion) and output (clearance) — it does NOT depend on Vd.",
      arithmetic: "Step 1: Css = rate/CL. Step 2: 12 mg/h ÷ 4 L/h = 3 mg/L (the per-hour cancels).",
      unit: "State mg/L.",
    },
  },
  {
    id: "calc-free-drug", topic: "B5 · Pharmacokinetics", lecture: "L10", source: "core",
    type: "calc", marks: 2,
    stem: "A drug is 90% bound to plasma proteins. If the total plasma concentration is 20 mg/L, calculate the free (unbound) drug concentration.",
    formula: "free fraction = 1 − fraction bound;  free conc = free fraction × total conc",
    steps: ["Free fraction = 1 − 0.90 = 0.10 (10%).", "Free conc = 0.10 × 20 mg/L.", "= 2 mg/L."],
    answer: 2, unit: "mg/L", tolerance: 0.1,
    feedback: {
      conceptual: "Only free (unbound) drug is pharmacologically active and able to distribute, be metabolised or be filtered. Highly protein-bound drugs (e.g. warfarin ~99% bound) have very little free drug.",
      arithmetic: "Step 1: if 90% is bound, 10% is free → free fraction = 0.10. Step 2: 0.10 × 20 mg/L = 2 mg/L.",
      unit: "State mg/L.",
    },
  },
  {
    id: "calc-efflux-ratio", topic: "B5 · Pharmacokinetics", lecture: "L10", source: "core",
    type: "calc", marks: 2,
    stem: "In a Caco-2 permeability study, the apparent permeability basolateral→apical (Papp B→A) is 12 ×10⁻⁶ cm/s and apical→basolateral (Papp A→B) is 3 ×10⁻⁶ cm/s. Calculate the efflux ratio and state whether efflux is significant.",
    formula: "Efflux ratio = Papp(B→A) / Papp(A→B);  significant if > 3",
    steps: ["Efflux ratio = 12 / 3 = 4.", "4 > 3, so efflux IS significant (suggests a substrate of an efflux transporter, e.g. P-gp)."],
    answer: 4, unit: "(efflux ratio)", tolerance: 0.1,
    feedback: {
      conceptual: "If a drug is pumped back out (e.g. by P-glycoprotein), the B→A permeability exceeds A→B. An efflux ratio >3 indicates significant efflux, which can limit oral absorption and CNS penetration.",
      arithmetic: "Step 1: efflux ratio = Papp(B→A)/Papp(A→B). Step 2: 12 ÷ 3 = 4. Step 3: compare with the threshold of 3 → 4 > 3 = significant efflux.",
      unit: "The ratio is dimensionless (the ×10⁻⁶ cm/s units cancel).",
    },
  },
  {
    id: "calc-hh-ratio", topic: "B5 · Pharmacokinetics", lecture: "L10", source: "core",
    type: "calc", marks: 3,
    stem: "A weakly acidic drug has a pKa of 3.4. In the stomach (pH 1.4), calculate the ratio of unionised to ionised drug. What does this imply for its absorption?",
    formula: "For an acid: log([ionised]/[unionised]) = pH − pKa",
    steps: ["pH − pKa = 1.4 − 3.4 = −2.", "log([ionised]/[unionised]) = −2 → [ionised]/[unionised] = 10⁻² = 0.01.", "So unionised : ionised = 100 : 1 — mostly unionised, so the weak acid is well absorbed from the stomach."],
    answer: 100, unit: "(unionised:ionised)", tolerance: 2,
    feedback: {
      conceptual: "Only the UNIONISED form crosses membranes. For a weak acid in acidic conditions (pH below pKa), most drug is unionised → good gastric absorption (this is why aspirin, a weak acid, is partly absorbed in the stomach). The Henderson–Hasselbalch equation for an acid is pH = pKa + log([ionised A⁻]/[unionised HA]).",
      arithmetic: "Step 1: pH − pKa = 1.4 − 3.4 = −2. Step 2: log([ionised]/[unionised]) = −2, so [ionised]/[unionised] = 10⁻² = 0.01. Step 3: invert to express unionised:ionised = 1/0.01 = 100, i.e. 100:1.",
      unit: "The answer is a ratio (unionised : ionised) ≈ 100 : 1; it is dimensionless.",
    },
  },
];

if (typeof window !== "undefined") window.CALC_BANK = CALC_BANK;
