// questions.js — Topic taxonomy (the 8 teaching blocks), block metadata, and MCQs.
//
// The canonical topic list is TOPICS (one entry per block). Every SAQ, MCQ,
// calculation and case study is tagged with one of these block names so it
// participates in topic filtering, SRS, mastery and analytics together.
//
// app.js merges SAQ_BANK (saqs.js), CALC_BANK (calcs.js) and CASE_BANK
// (cases.js) into the global QUESTION_BANK at boot.

const TOPICS = [
  "B1 · Drug Targets & Discovery",
  "B2 · Mechanisms of Drug Action",
  "B3 · Methods in Drug Discovery",
  "B4 · Lead Discovery & Biomarkers",
  "B5 · Pharmacokinetics",
  "B6 · Preclinical & Safety",
  "B7 · Pharmaceutical Dev & Clinical Evaluation",
  "B8 · 21st-Century Approaches",
];

// Richer metadata for the block picker (lectures inside each block).
const BLOCKS = [
  { topic: "B1 · Drug Targets & Discovery", n: 1, lectures: ["Drug targets & drug discovery (L02)"] },
  { topic: "B2 · Mechanisms of Drug Action", n: 2, lectures: ["Properties of drugs: agonists → inverse agonists (L03)"] },
  { topic: "B3 · Methods in Drug Discovery", n: 3, lectures: ["Molecular biology methods (L04)", "Assay techniques (L05)"] },
  { topic: "B4 · Lead Discovery & Biomarkers", n: 4, lectures: ["Lead generation (L06)", "Lead optimisation (L07)", "Biomarkers (L08)", "Case study: drugs to treat pain"] },
  { topic: "B5 · Pharmacokinetics", n: 5, lectures: ["ADME: absorption & distribution (L10)", "ADME: metabolism & excretion (L11)", "Pharmacogenomics (L12)"] },
  { topic: "B6 · Preclinical & Safety", n: 6, lectures: ["Properties of drugs: in vivo studies (L13)", "Preclinical safety assessment (L14)"] },
  { topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", n: 7, lectures: ["Pharmaceutical development", "Clinical evaluation of drugs"] },
  { topic: "B8 · 21st-Century Approaches", n: 8, lectures: ["Biologics, immunotherapies & PROTACs", "Drug repurposing & AI in drug development"] },
];

// ---------------------------------------------------------------------------
// MCQ_BANK — quick single-best-answer items for fast active recall.
// Shape: { id, topic, type:"mcq", question, options:[...], answer:<index>,
//          explanation, source? }
// ---------------------------------------------------------------------------
const MCQ_BANK = [
  // ---- B1 ----
  { id: "mcq-b1-1", topic: "B1 · Drug Targets & Discovery", type: "mcq",
    question: "Which set best describes the four criteria of a good drug target?",
    options: [
      "Cheap, patentable, oral, small",
      "Efficacious, safe, clinically/commercially needed, druggable",
      "Hydrophilic, abundant, intracellular, enzymatic",
      "Novel, lipophilic, membrane-bound, human-specific"],
    answer: 1,
    explanation: "A good target is efficacious (modulation changes the disease), safe, clinically and commercially needed, and druggable." },
  { id: "mcq-b1-2", topic: "B1 · Drug Targets & Discovery", type: "mcq",
    question: "Imatinib (Glivec) for CML is a classic example of which discovery approach?",
    options: ["Phenotypic screening", "Serendipity", "Molecular (target-based) approach", "Natural-product screening"],
    answer: 2,
    explanation: "The Bcr-Abl fusion kinase (Philadelphia chromosome) was identified as the driver, then an in vitro kinase assay screened for inhibitors — a rational molecular approach." },
  { id: "mcq-b1-3", topic: "B1 · Drug Targets & Discovery", type: "mcq",
    question: "Roughly what proportion of marketed drugs act on GPCRs?",
    options: ["~3%", "~15%", "~34%", "~80%"],
    answer: 2,
    explanation: "GPCRs are the single largest target class, accounting for around a third of approved drugs, because they are cell-surface, druggable and central to many pathways." },

  // ---- B2 ----
  { id: "mcq-b2-1", topic: "B2 · Mechanisms of Drug Action", type: "mcq",
    question: "A non-competitive antagonist typically has which effect on an agonist concentration–response curve?",
    options: ["Shifts EC50 right, Emax unchanged", "EC50 unchanged, Emax reduced", "Both EC50 and Emax increase", "No change to either"],
    answer: 1,
    explanation: "Non-competitive (insurmountable) antagonism removes functional receptors, lowering Emax; because it doesn't compete at the orthosteric site, EC50 is largely unchanged." },
  { id: "mcq-b2-2", topic: "B2 · Mechanisms of Drug Action", type: "mcq",
    question: "Only one of the following ligand types possesses intrinsic efficacy. Which?",
    options: ["Neutral antagonist", "Agonist", "Both possess it equally", "Neither possesses it"],
    answer: 1,
    explanation: "Both agonists and antagonists have affinity (they bind), but only agonists have intrinsic efficacy — the ability to activate the receptor and produce a response." },
  { id: "mcq-b2-3", topic: "B2 · Mechanisms of Drug Action", type: "mcq",
    question: "An inverse agonist requires which receptor property to act?",
    options: ["Spare receptors", "Constitutive (agonist-independent) activity", "A second messenger", "An allosteric site"],
    answer: 1,
    explanation: "An inverse agonist reduces basal signalling, so the receptor must have constitutive activity for the effect to be observable; a pure antagonist has no effect on basal tone." },

  // ---- B3 ----
  { id: "mcq-b3-1", topic: "B3 · Methods in Drug Discovery", type: "mcq",
    question: "Which assay format is best suited to primary high-throughput screening?",
    options: ["Isolated organ-bath bioassay", "Whole-animal in vivo study", "Ligand-binding (e.g. radioligand displacement) assay", "Patch-clamp electrophysiology"],
    answer: 2,
    explanation: "Binding assays are simple, robust, cheap and scalable to HTS — though they cannot distinguish agonist from antagonist, which is why functional assays follow." },
  { id: "mcq-b3-2", topic: "B3 · Methods in Drug Discovery", type: "mcq",
    question: "In CRISPR/Cas9 editing, the role of the guide RNA is to:",
    options: ["Cut the DNA", "Provide the repair template", "Direct Cas9 to the complementary target sequence", "Ligate the broken ends"],
    answer: 2,
    explanation: "The gRNA base-pairs with the target DNA and recruits Cas9, which then makes the double-strand break; repair (NHEJ or HDR) then knocks out or edits the gene." },
  { id: "mcq-b3-3", topic: "B3 · Methods in Drug Discovery", type: "mcq",
    question: "Why are reporter genes useful in drug-screening assays?",
    options: [
      "They are toxic to non-responding cells",
      "Their product is easily and quantitatively measurable and not normally expressed by the cell",
      "They permanently edit the genome",
      "They block off-target receptors"],
    answer: 1,
    explanation: "A reporter gene placed under the control of a pathway gives an easily measured signal (e.g. luciferase, GFP); because cells don't normally express it, background is low." },

  // ---- B4 ----
  { id: "mcq-b4-1", topic: "B4 · Lead Discovery & Biomarkers", type: "mcq",
    question: "Lipinski's Rule of 5 does NOT include which criterion?",
    options: ["MW < 500 Da", "logP < 5", "≤5 H-bond donors", "Melting point > 100 °C"],
    answer: 3,
    explanation: "The rule covers MW < 500, logP < 5, ≤5 H-bond donors and ≤10 H-bond acceptors; melting point is not part of it." },
  { id: "mcq-b4-2", topic: "B4 · Lead Discovery & Biomarkers", type: "mcq",
    question: "In the lead-generation pipeline, a 'hit' is best defined as a compound that:",
    options: [
      "Shows any effect in a primary screen",
      "Shows the desired mechanism (e.g. antagonism/inhibition)",
      "Is ready for clinical trials",
      "Has passed toxicology"],
    answer: 1,
    explanation: "Active = any effect; hit = the desired mechanism confirmed; lead = a hit amenable to optimisation toward a candidate." },
  { id: "mcq-b4-3", topic: "B4 · Lead Discovery & Biomarkers", type: "mcq",
    question: "CD4+ count and HIV viral load are examples of which biomarker use?",
    options: ["Safety biomarker", "Surrogate endpoint", "Susceptibility biomarker", "Diagnostic only"],
    answer: 1,
    explanation: "They substitute for the true clinical endpoint (progression to AIDS/death), allowing efficacy to be judged in months rather than years." },

  // ---- B5 ----
  { id: "mcq-b5-1", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "A drug with Vd far larger than total body water (~42 L) is most likely:",
    options: ["Confined to plasma", "Distributed only in extracellular fluid", "Extensively tissue-bound / lipophilic", "Not absorbed"],
    answer: 2,
    explanation: "A large apparent Vd implies the drug partitions extensively into tissues, leaving little in plasma — typical of lipophilic, tissue-bound drugs." },
  { id: "mcq-b5-2", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "Which equation correctly relates half-life to Vd and clearance?",
    options: ["t½ = CL / (0.693 × Vd)", "t½ = 0.693 × Vd / CL", "t½ = 0.693 × CL / Vd", "t½ = Vd × CL / 0.693"],
    answer: 1,
    explanation: "t½ = 0.693 × Vd / CL — half-life lengthens with larger Vd and shortens with higher clearance." },
  { id: "mcq-b5-3", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "Ethanol and high-dose phenytoin are eliminated by which kinetics?",
    options: ["First-order", "Zero-order (saturation)", "Mixed flip-flop", "None — they are not eliminated"],
    answer: 1,
    explanation: "When the metabolising enzyme is saturated, a constant amount (not fraction) is removed per unit time — zero-order kinetics." },
  { id: "mcq-b5-4", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "For codeine (a prodrug activated to morphine by CYP2D6), an ultrarapid metaboliser is at risk of:",
    options: ["No analgesia", "Excessive morphine and toxicity", "Slow absorption", "Reduced Vd"],
    answer: 1,
    explanation: "Ultrarapid CYP2D6 metabolisers convert codeine to morphine very quickly, risking dangerous morphine concentrations — the opposite problem occurs for active drugs cleared by CYP2D6." },

  // ---- B6 ----
  { id: "mcq-b6-1", topic: "B6 · Preclinical & Safety", type: "mcq",
    question: "The therapeutic index is conventionally calculated as:",
    options: ["ED50 / LD50", "LD50 / ED50", "LD50 × ED50", "LD50 − ED50"],
    answer: 1,
    explanation: "TI = LD50 (or TD50) / ED50 — a larger ratio implies a wider safety margin, though TI ignores curve slopes and idiosyncratic ADRs." },
  { id: "mcq-b6-2", topic: "B6 · Preclinical & Safety", type: "mcq",
    question: "The thalidomide tragedy primarily showed that:",
    options: [
      "Rodents over-predict human toxicity",
      "Species choice is critical — rodents are insensitive to its teratogenicity",
      "Genotoxicity tests are unnecessary",
      "Enantiomers always behave identically"],
    answer: 1,
    explanation: "Thalidomide is teratogenic in rabbits/primates but not rodents; modern reproductive toxicology therefore requires one rodent and one non-rodent species, and attention to chirality." },
  { id: "mcq-b6-3", topic: "B6 · Preclinical & Safety", type: "mcq",
    question: "The AMES test detects mutagenicity using:",
    options: [
      "Histidine-auxotrophic Salmonella reverting to prototrophy",
      "hERG channel current",
      "Micronucleus formation in lymphocytes",
      "Caco-2 permeability"],
    answer: 0,
    explanation: "Mutagens cause his⁻ Salmonella to revert to histidine prototrophy, producing colonies on histidine-free agar; ±S9 distinguishes parent vs metabolite mutagenicity." },

  // ---- B7 ----
  { id: "mcq-b7-1", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "An enteric coating is designed to:",
    options: [
      "Speed gastric dissolution",
      "Resist gastric pH but dissolve at the higher pH of the duodenum",
      "Increase particle size",
      "Mask the drug from CYP enzymes"],
    answer: 1,
    explanation: "Enteric (gastro-resistant) coatings protect acid-labile drugs (or protect the stomach from irritant drugs) by delaying release until the small intestine." },
  { id: "mcq-b7-2", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "Which clinical-trial phase first tests efficacy in patients with the target disease?",
    options: ["Phase 0", "Phase 1", "Phase 2", "Phase 4"],
    answer: 2,
    explanation: "Phase 1 focuses on safety in (usually healthy) volunteers; Phase 2 is the first test of efficacy and dose-finding in patients." },
  { id: "mcq-b7-3", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "In a double-blind trial, who is unaware of the treatment allocation?",
    options: ["The subject only", "The investigator only", "Both the subject and the investigator", "The subject, investigator and data analyst"],
    answer: 2,
    explanation: "Single = subject blinded; double = subject and investigator blinded; triple = subject, investigator and data analyst all blinded." },
  { id: "mcq-b7-4", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "Statistical power increases with which of the following?",
    options: ["Smaller sample size", "Larger effect size and larger sample size", "Higher P-value threshold only", "Use of a crossover design only"],
    answer: 1,
    explanation: "Power (probability of rejecting a false null) rises with both the number of subjects and the size of the effect being detected." },
  { id: "mcq-b7-5", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "Smaller drug particle size generally:",
    options: ["Decreases oral bioavailability", "Increases oral bioavailability", "Has no effect on dissolution", "Prevents absorption"],
    answer: 1,
    explanation: "Smaller particles have greater surface area, so dissolve faster; when dissolution is rate-limiting, oral bioavailability increases." },

  // ---- B8 ----
  { id: "mcq-b8-1", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "A PROTAC is best described as:",
    options: [
      "A monoclonal antibody",
      "A bifunctional molecule linking a target ligand to an E3 ligase ligand to drive degradation",
      "A single-domain enzyme inhibitor",
      "A lipid nanoparticle"],
    answer: 1,
    explanation: "PROTACs are bifunctional: one warhead binds the target, the other recruits an E3 ubiquitin ligase, tagging the target for proteasomal degradation; they act catalytically and sub-stoichiometrically." },
  { id: "mcq-b8-2", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "Humanisation of a therapeutic monoclonal antibody is performed mainly to:",
    options: ["Increase its molecular weight", "Reduce immunogenicity", "Allow oral dosing", "Shorten its half-life"],
    answer: 1,
    explanation: "Humanisation replaces rodent framework sequence with human sequence to reduce anti-drug antibody responses; Fc engineering and affinity maturation tune function and potency." },
  { id: "mcq-b8-3", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "BenevolentAI used AI to repurpose which drug for COVID-19 by predicting AAK1 inhibition?",
    options: ["Remdesivir", "Dexamethasone", "Baricitinib", "Tocilizumab"],
    answer: 2,
    explanation: "Their knowledge graph flagged baricitinib (a JAK inhibitor) as an AAK1 inhibitor that could block viral endocytosis and dampen the cytokine storm; it later gained FDA authorisation." },
  { id: "mcq-b8-4", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "The 'hook effect' seen with PROTACs at high concentrations occurs because:",
    options: [
      "The drug is metabolised faster",
      "Excess PROTAC saturates target and E3 ligase separately, preventing productive ternary complex formation",
      "The proteasome is inhibited",
      "The linker is too short"],
    answer: 1,
    explanation: "At high PROTAC concentrations the two warheads bind target and E3 ligase on separate molecules, so the productive ternary complex needed for ubiquitination falls — degradation decreases." },
  { id: "mcq-b8-5", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "Compared with de novo development, drug repurposing is attractive mainly because it is:",
    options: ["More novel", "Faster, cheaper and lower-risk (safety/PK already known)", "Always more effective", "Exempt from clinical trials"],
    answer: 1,
    explanation: "Repurposed drugs already have safety, PK and manufacturing data, cutting time (~3–8 vs 10–15 yr) and cost and lowering attrition risk." },

  // =====================================================================
  // EXTENDED MCQ BANK (added from lecture notes + 2023/2024 past papers)
  // =====================================================================

  // ---- B1 (extended) ----
  { id: "mcq-b1-4", topic: "B1 · Drug Targets & Discovery", type: "mcq",
    question: "Glyceryl trinitrate (GTN), used for angina since 1879, illustrates which discovery approach?",
    options: ["Molecular (target-based) approach", "Phenotypic (observation-led) approach", "Combinatorial chemistry", "Antibody phage display"],
    answer: 1,
    explanation: "GTN's vasodilator effect was exploited clinically for over a century before its mechanism (NO release) was understood — a classic phenotypic, effect-first discovery." },
  { id: "mcq-b1-5", topic: "B1 · Drug Targets & Discovery", type: "mcq",
    question: "GTN is a prodrug that exerts its effect after being converted in the body to:",
    options: ["cAMP", "Nitric oxide (NO)", "cGMP directly", "Acetylcholine"],
    answer: 1,
    explanation: "GTN → NO, which activates soluble guanylyl cyclase → ↑cGMP → PKG → ↓intracellular Ca²⁺ → smooth-muscle relaxation and vasodilation." },
  { id: "mcq-b1-6", topic: "B1 · Drug Targets & Discovery", type: "mcq",
    question: "The Philadelphia chromosome (driving most CML) arises from a reciprocal translocation between chromosomes:",
    options: ["21 and 22", "9 and 22", "11 and 14", "X and 9"],
    answer: 1,
    explanation: "t(9;22) creates the constitutively active Bcr-Abl fusion tyrosine kinase; imatinib was identified as an inhibitor in a kinase assay." },
  { id: "mcq-b1-7", topic: "B1 · Drug Targets & Discovery", type: "mcq",
    question: "Sildenafil (Viagra) is best described as an example of:",
    options: ["Pure rational design", "Serendipity / repurposing during a molecular programme", "Natural-product screening", "Combinatorial chemistry"],
    answer: 1,
    explanation: "Developed as a PDE5 inhibitor for angina (a disappointing failure), volunteers reported improved erections — leading to repurposing for erectile dysfunction (and later pulmonary arterial hypertension)." },
  { id: "mcq-b1-8", topic: "B1 · Drug Targets & Discovery", type: "mcq",
    question: "An unwanted effect caused by the drug acting on its intended target is termed:",
    options: ["An off-target adverse effect", "An on-target adverse effect", "An idiosyncratic reaction", "A first-pass effect"],
    answer: 1,
    explanation: "On-target adverse effects arise from the target itself; off-target effects arise from interaction with other molecules." },
  { id: "mcq-b1-9", topic: "B1 · Drug Targets & Discovery", type: "mcq",
    question: "Which technique validates a target by reducing expression of its gene?",
    options: ["siRNA knockdown", "ELISA", "HPLC", "Northern blotting alone"],
    answer: 0,
    explanation: "siRNA knockdown (or a transgenic knockout) tests the functional consequence of losing the gene product, helping confirm the target's role in disease." },
  { id: "mcq-b1-10", topic: "B1 · Drug Targets & Discovery", type: "mcq",
    question: "Risdiplam, a modern treatment for spinal muscular atrophy, was discovered by:",
    options: ["Target-based kinase screening", "Phenotypic screening for motor-neurone survival", "Antibody phage display", "Natural-product isolation"],
    answer: 1,
    explanation: "Phenotypic screens identified small molecules that modify SMN2 splicing (stabilising U1 snRNP at exon 7) to raise full-length SMN — a modern phenotypic success." },
  { id: "mcq-b1-11", topic: "B1 · Drug Targets & Discovery", type: "mcq",
    question: "Developing a drug against a brand-new, previously unexploited target is described as a:",
    options: ["Best-in-class (me-too) strategy", "First-in-class strategy", "Biosimilar strategy", "Generic strategy"],
    answer: 1,
    explanation: "First-in-class targets novel biology (high risk, potential blockbuster); best-in-class improves on an already-validated target (lower risk, but competitive)." },
  { id: "mcq-b1-12", topic: "B1 · Drug Targets & Discovery", type: "mcq",
    question: "Approximately how many G-protein-coupled receptors are encoded in the human genome?",
    options: ["~80", "~200", "~800", "~8000"],
    answer: 2,
    explanation: "~800 GPCRs make them the largest receptor superfamily (about half are sensory); their cell-surface location and druggable pockets explain why roughly a third of drugs target them." },

  // ---- B2 (extended) ----
  { id: "mcq-b2-4", topic: "B2 · Mechanisms of Drug Action", type: "mcq",
    question: "Which property is possessed by BOTH agonists and antagonists?",
    options: ["Intrinsic efficacy", "Affinity", "Negative efficacy", "Constitutive activity"],
    answer: 1,
    explanation: "Both bind the receptor (affinity); only agonists have intrinsic efficacy — the ability to activate the receptor and produce a response." },
  { id: "mcq-b2-5", topic: "B2 · Mechanisms of Drug Action", type: "mcq",
    question: "Buprenorphine, used in opioid dependence, is best classified as a:",
    options: ["Full µ-agonist", "Partial µ-agonist", "Inverse agonist", "Irreversible antagonist"],
    answer: 1,
    explanation: "It is a partial agonist at the µ-opioid (MOP) receptor and can act as a functional antagonist toward full agonists." },
  { id: "mcq-b2-6", topic: "B2 · Mechanisms of Drug Action", type: "mcq",
    question: "A competitive (reversible) antagonist alters the agonist concentration–response curve by:",
    options: ["Shifting it right with reduced Emax", "Shifting it right with Emax unchanged (surmountable)", "Shifting it left with increased Emax", "Having no effect"],
    answer: 1,
    explanation: "Competitive antagonism is surmountable: more agonist overcomes it, so Emax is preserved — distinct from non-competitive antagonism, which lowers Emax." },
  { id: "mcq-b2-7", topic: "B2 · Mechanisms of Drug Action", type: "mcq",
    question: "Spare receptors (receptor reserve) are inferred when:",
    options: ["EC50 = Kd", "EC50 > Kd", "EC50 < Kd", "Bmax = 0"],
    answer: 2,
    explanation: "Signal amplification allows a maximal response at well below 100% occupancy, so EC50 lies below Kd." },
  { id: "mcq-b2-8", topic: "B2 · Mechanisms of Drug Action", type: "mcq",
    question: "Oliceridine is a G-protein-biased µ-opioid agonist; the rationale is that β-arrestin signalling at MOP mediates:",
    options: ["Analgesia", "Respiratory depression, nausea and constipation", "Receptor synthesis", "Increased affinity"],
    answer: 1,
    explanation: "The G-protein arm drives analgesia while the β-arrestin arm drives respiratory depression/nausea/constipation; bias aims to separate benefit from harm." },
  { id: "mcq-b2-9", topic: "B2 · Mechanisms of Drug Action", type: "mcq",
    question: "A superagonist is a ligand that produces:",
    options: ["A response equal to the endogenous agonist", "A maximal response greater than the endogenous agonist", "No response alone", "A response below baseline"],
    answer: 1,
    explanation: "It drives the receptor into a distinct, highly responsive conformation (e.g. isotonitazene) — evidence that receptors adopt more than two states." },
  { id: "mcq-b2-10", topic: "B2 · Mechanisms of Drug Action", type: "mcq",
    question: "Benzodiazepines such as diazepam act at GABA-A receptors as:",
    options: ["Orthosteric agonists", "Positive allosteric modulators (PAMs)", "Inverse agonists", "Competitive antagonists"],
    answer: 1,
    explanation: "They bind a distinct allosteric site and enhance the effect of GABA — a classic PAM." },
  { id: "mcq-b2-11", topic: "B2 · Mechanisms of Drug Action", type: "mcq",
    question: "In the two-state model, an agonist produces its effect by:",
    options: ["Binding R and R* equally", "Binding with higher affinity to R* and stabilising it", "Binding R and reducing R*", "Binding only the allosteric site"],
    answer: 1,
    explanation: "An agonist preferentially binds and stabilises the active R* state, shifting the equilibrium toward R* and increasing response." },
  { id: "mcq-b2-12", topic: "B2 · Mechanisms of Drug Action", type: "mcq",
    question: "A silent (neutral) allosteric modulator (SAM):",
    options: ["Enhances the agonist's effect", "Suppresses the agonist's effect", "Occupies the allosteric site without altering orthosteric affinity/efficacy (and blocks PAMs/NAMs)", "Reduces basal activity"],
    answer: 2,
    explanation: "A SAM occupies the allosteric site, preventing PAM/NAM binding, but does not itself change orthosteric binding, affinity or efficacy." },

  // ---- B3 (extended) ----
  { id: "mcq-b3-4", topic: "B3 · Methods in Drug Discovery", type: "mcq",
    question: "Which is a radioisotope commonly used to label a radioligand?",
    options: ["Carbon-12", "Tritium (³H)", "Nitrogen-14", "Oxygen-16"],
    answer: 1,
    explanation: "³H, ¹²⁵I and ³⁵S are common radioligand labels; the assay measures bound radioactivity after separating bound from free ligand." },
  { id: "mcq-b3-5", topic: "B3 · Methods in Drug Discovery", type: "mcq",
    question: "In a radioligand binding assay, specific binding is calculated as:",
    options: ["Total binding + non-specific binding", "Total binding − non-specific binding (defined with excess cold ligand)", "Non-specific binding alone", "The bound/free ratio"],
    answer: 1,
    explanation: "Excess unlabelled ('cold') ligand displaces radioligand from specific (saturable) sites but not non-specific (non-saturable) sites, defining NSB to subtract." },
  { id: "mcq-b3-6", topic: "B3 · Methods in Drug Discovery", type: "mcq",
    question: "The principal advantage of the scintillation proximity assay (SPA) is that:",
    options: ["It measures efficacy", "It does not require separation of bound from free ligand", "It uses no radioactivity", "It distinguishes agonists from antagonists"],
    answer: 1,
    explanation: "Only bead-bound radioligand transfers energy to the scintillant to emit light, so free ligand need not be washed away — ideal for HTS." },
  { id: "mcq-b3-7", topic: "B3 · Methods in Drug Discovery", type: "mcq",
    question: "The GTP-γ-S assay can distinguish agonists from antagonists because GTP-γ-S:",
    options: ["Is hydrolysed faster than GTP", "Is non-hydrolysable and traps Gα in its active state", "Blocks the receptor", "Labels DNA"],
    answer: 1,
    explanation: "Agonists increase GTP-γ-S incorporation (a measure of efficacy); antagonists do not, and block agonist-driven incorporation." },
  { id: "mcq-b3-8", topic: "B3 · Methods in Drug Discovery", type: "mcq",
    question: "Which is a QUANTAL (all-or-none) response?",
    options: ["Smooth-muscle contraction to ACh", "Fall in blood glucose to insulin", "The % of animals developing seizures after a drug", "Graded pain relief"],
    answer: 2,
    explanation: "Quantal responses are yes/no per individual (e.g. % showing a seizure or adverse reaction); the others are graded responses of varying amplitude." },
  { id: "mcq-b3-9", topic: "B3 · Methods in Drug Discovery", type: "mcq",
    question: "Insulin potency is standardised in International Units (IU) rather than by mass because:",
    options: ["It is radioactive", "Equal masses from different batches can have different potencies (modifications/MW)", "It cannot be dissolved", "It is a small molecule"],
    answer: 1,
    explanation: "A bioassay against a WHO standard quantifies biological activity when chemical mass does not reliably reflect potency." },
  { id: "mcq-b3-10", topic: "B3 · Methods in Drug Discovery", type: "mcq",
    question: "In CRISPR/Cas9, homology-directed repair (HDR) differs from NHEJ in that HDR:",
    options: ["Always knocks the gene out", "Requires a repair template to introduce a defined edit (knock-in/correction)", "Cuts the DNA", "Needs no Cas9"],
    answer: 1,
    explanation: "NHEJ rejoins ends imprecisely (indels → knockout); HDR uses a supplied template for a precise knock-in or correction." },
  { id: "mcq-b3-11", topic: "B3 · Methods in Drug Discovery", type: "mcq",
    question: "An 'orphan' receptor is one that:",
    options: ["Has no gene", "Has no known endogenous ligand at the time of discovery", "Cannot be expressed in cells", "Is found only in bacteria"],
    answer: 1,
    explanation: "Orphan receptors are identified by sequence homology to known families; their ligands are found by 'deorphanisation' (reverse pharmacology)." },
  { id: "mcq-b3-12", topic: "B3 · Methods in Drug Discovery", type: "mcq",
    question: "Why are bacterial (E. coli) expression systems often unsuitable for complex human therapeutic proteins?",
    options: ["They are too expensive", "They cannot perform eukaryotic post-translational modifications such as glycosylation (and may misfold protein)", "They grow too slowly", "They cannot be transfected"],
    answer: 1,
    explanation: "Bacteria lack glycosylation/correct folding, may form inactive inclusion bodies and carry endotoxin — so mammalian (CHO) cells are often used." },
  { id: "mcq-b3-13", topic: "B3 · Methods in Drug Discovery", type: "mcq",
    question: "Conditional (tissue- or time-specific) gene knockouts are commonly generated using:",
    options: ["Cre-lox recombination", "PCR alone", "ELISA", "Edman degradation"],
    answer: 0,
    explanation: "Cre-lox recombination gives precise spatial/temporal control, avoiding the embryonic lethality or compensation seen with global knockouts." },

  // ---- B4 (extended) ----
  { id: "mcq-b4-4", topic: "B4 · Lead Discovery & Biomarkers", type: "mcq",
    question: "Combinatorial chemistry is used to:",
    options: ["Purify natural products", "Rapidly generate large numbers of structurally related compounds", "Sequence proteins", "Measure potency"],
    answer: 1,
    explanation: "It generates tens of thousands to millions of related compounds; diversity is introduced by clever design of the starting building blocks." },
  { id: "mcq-b4-5", topic: "B4 · Lead Discovery & Biomarkers", type: "mcq",
    question: "Compared with synthetic libraries, natural products are especially valued for their:",
    options: ["Low cost", "Reproducible supply", "Structural diversity and novelty", "High oral bioavailability"],
    answer: 2,
    explanation: "Unexpected scaffolds raise the chance of hitting a new target, though supply, reproducibility and scalability can be problematic." },
  { id: "mcq-b4-6", topic: "B4 · Lead Discovery & Biomarkers", type: "mcq",
    question: "Captopril (an ACE inhibitor) is historically notable as:",
    options: ["The first natural-product drug", "The first drug discovered from knowledge of the target's structure (rational design)", "The first biologic", "The first prodrug"],
    answer: 1,
    explanation: "It is the classic example of rational, structure-based design from knowledge of the enzyme target." },
  { id: "mcq-b4-7", topic: "B4 · Lead Discovery & Biomarkers", type: "mcq",
    question: "Which is a desirable property of a lead compound?",
    options: ["Extremely high lipophilicity", "Presence of known toxicophores", "Amenability to chemical modification", "Irreversible binding is essential"],
    answer: 2,
    explanation: "Leads should be modifiable to improve potency/selectivity/ADME, avoid toxic groups, and ideally bind reversibly; they need not be highly potent initially." },
  { id: "mcq-b4-8", topic: "B4 · Lead Discovery & Biomarkers", type: "mcq",
    question: "The Veber rules add which criteria to predictions of good oral bioavailability?",
    options: ["≤10 rotatable bonds and polar surface area ≤140 Å²", "Melting point >100 °C", "≤3 aromatic rings", "logP >5"],
    answer: 0,
    explanation: "Veber's criteria (rotatable-bond count and PSA) complement Lipinski's Rule of 5." },
  { id: "mcq-b4-9", topic: "B4 · Lead Discovery & Biomarkers", type: "mcq",
    question: "A target-engagement biomarker (e.g. PET radioligand displacement) tells you that:",
    options: ["The drug is being metabolised", "The drug physically interacts with (occupies) its target, without functional information", "The disease has resolved", "The drug is toxic"],
    answer: 1,
    explanation: "For example, antipsychotics need ≈65% D2-receptor occupancy for efficacy; PET/SPECT measure occupancy early to guide dosing." },
  { id: "mcq-b4-10", topic: "B4 · Lead Discovery & Biomarkers", type: "mcq",
    question: "cAMP measured by ELISA after dosing a GPCR-targeted drug is an example of which biomarker?",
    options: ["Diagnostic biomarker", "Mechanism (pharmacodynamic) biomarker", "Susceptibility biomarker", "Safety biomarker"],
    answer: 1,
    explanation: "It reports a downstream functional consequence of target engagement (proof of mechanism)." },
  { id: "mcq-b4-11", topic: "B4 · Lead Discovery & Biomarkers", type: "mcq",
    question: "A companion diagnostic differs from a complementary diagnostic in that a companion diagnostic is:",
    options: ["Optional and informative only", "Essential to identify patients who should (or should not) receive the drug before it is prescribed", "Only used after marketing", "A safety test only"],
    answer: 1,
    explanation: "Companion = essential to the prescribing decision; complementary = informative (e.g. on side-effect risk) but not essential." },
  { id: "mcq-b4-12", topic: "B4 · Lead Discovery & Biomarkers", type: "mcq",
    question: "Empirical (high-throughput) screening is the approach of choice when:",
    options: ["The target structure and a ligand are both known", "Nothing is known about the target structure or its ligands", "Only biologics are wanted", "The drug must be a prodrug"],
    answer: 1,
    explanation: "It makes no structural assumptions and screens large, diverse libraries — historically yielding many first-in-class drugs (and can reveal unexpected SAR even when the target is known)." },

  // ---- B5 (extended) ----
  { id: "mcq-b5-5", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "By definition, which route gives a bioavailability (F) of 1 (100%)?",
    options: ["Oral", "Intravenous", "Subcutaneous", "Transdermal"],
    answer: 1,
    explanation: "IV delivers drug directly into the systemic circulation; oral F is <1 because of incomplete absorption and first-pass metabolism." },
  { id: "mcq-b5-6", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "Approximately what is the total body water of a 70 kg adult (a useful Vd reference)?",
    options: ["~5 L", "~12 L", "~42 L", "~100 L"],
    answer: 2,
    explanation: "Plasma ≈3 L, blood ≈5.5 L, extracellular fluid ≈12 L and total body water ≈42 L; a Vd far above 42 L implies extensive tissue binding." },
  { id: "mcq-b5-7", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "Only which form of a weakly acidic or basic drug readily crosses lipid membranes by passive diffusion?",
    options: ["The ionised form", "The unionised form", "The protein-bound form", "The glucuronidated form"],
    answer: 1,
    explanation: "Only the lipid-soluble unionised species diffuses passively; the pH and the drug's pKa (Henderson-Hasselbalch) set the ionised:unionised ratio." },
  { id: "mcq-b5-8", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "P-glycoprotein (P-gp) is:",
    options: ["A plasma-binding protein", "An ABC-family efflux transporter that causes multidrug resistance", "A cytochrome P450 enzyme", "A reporter gene"],
    answer: 1,
    explanation: "P-gp effluxes drugs out of cells (gut, blood–brain barrier, tumour cells); an efflux ratio >3 indicates significant efflux." },
  { id: "mcq-b5-9", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "Warfarin is ~99% bound to plasma albumin, so it is expected to have a:",
    options: ["Very high Vd", "Low Vd (~8 L)", "Negative Vd", "Vd equal to total body water"],
    answer: 1,
    explanation: "Strong plasma-protein binding holds the drug in the vascular compartment, giving a low apparent volume of distribution." },
  { id: "mcq-b5-10", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "Clearance is best defined as:",
    options: ["The fraction of drug absorbed", "The volume of plasma cleared of drug per unit time", "The time for the concentration to halve", "The dose required for an effect"],
    answer: 1,
    explanation: "CL links dose rate and steady-state concentration (at steady state, dose rate = CL × Css)." },
  { id: "mcq-b5-11", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "Phase I drug metabolism most commonly involves:",
    options: ["Glucuronidation", "Oxidation by cytochrome P450", "Sulphation", "Acetylation"],
    answer: 1,
    explanation: "Phase I = functionalisation (oxidation/reduction/hydrolysis, often CYP450); Phase II = conjugation (glucuronidation, sulphation, etc.)." },
  { id: "mcq-b5-12", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "Which two cytochrome P450 enzymes together metabolise more than half of all drugs?",
    options: ["CYP1A1 + CYP2E1", "CYP3A4 + CYP2D6", "CYP4A + CYP2B6", "CYP2A6 + CYP2C8"],
    answer: 1,
    explanation: "CYP3A4 and CYP2D6 handle >50% of drugs; CYP2D6 is highly polymorphic, causing inter-individual variation." },
  { id: "mcq-b5-13", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "The main excretory route for water-soluble drugs and metabolites is:",
    options: ["The lungs", "Bile and faeces", "The kidney (urine)", "Sweat"],
    answer: 2,
    explanation: "Renal handling combines glomerular filtration, active tubular secretion (e.g. via OATs) and passive reabsorption; lipid-soluble drugs favour biliary excretion." },
  { id: "mcq-b5-14", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "A CYP2D6 poor metaboliser given a drug that is INACTIVATED by CYP2D6 is most likely to have:",
    options: ["Lower plasma levels and reduced effect", "Higher plasma levels and increased risk of toxicity", "No change", "Faster clearance"],
    answer: 1,
    explanation: "Reduced metabolism lets the active drug accumulate (≈7% of Caucasians are PMs and need lower doses); the opposite problem occurs for a CYP2D6-activated prodrug such as codeine." },
  { id: "mcq-b5-15", topic: "B5 · Pharmacokinetics", type: "mcq",
    question: "HLA-B*57:01 genotyping is performed before prescribing which drug?",
    options: ["Warfarin", "Abacavir", "Codeine", "Simvastatin"],
    answer: 1,
    explanation: "HLA-B*57:01 carriers are at risk of abacavir hypersensitivity syndrome; abacavir is contraindicated in carriers — a leading example of translational pharmacogenetics." },

  // ---- B6 (extended) ----
  { id: "mcq-b6-4", topic: "B6 · Preclinical & Safety", type: "mcq",
    question: "Which of the 3Rs refers to using the smallest number of animals consistent with the experimental design?",
    options: ["Replacement", "Reduction", "Refinement", "Restriction"],
    answer: 1,
    explanation: "Reduction is achieved through better statistics, imaging that allows repeat measures, and data/resource sharing." },
  { id: "mcq-b6-5", topic: "B6 · Preclinical & Safety", type: "mcq",
    question: "The AMES test for mutagenicity is an example of which 'R'?",
    options: ["Reduction", "Refinement", "Replacement (an absolute non-animal alternative)", "It is not part of the 3Rs"],
    answer: 2,
    explanation: "It is an in vitro genotoxicity test that replaces animal use — an absolute replacement, alongside computer modelling and human volunteers." },
  { id: "mcq-b6-6", topic: "B6 · Preclinical & Safety", type: "mcq",
    question: "UK animal research is regulated under which legislation?",
    options: ["Medicines Act 1968", "Animals (Scientific Procedures) Act 1986 (ASPA)", "Misuse of Drugs Act 1971", "Human Tissue Act 2004"],
    answer: 1,
    explanation: "ASPA is administered by the Home Office (Animals in Science Regulation Unit); three licences (establishment, project, personal) are required." },
  { id: "mcq-b6-7", topic: "B6 · Preclinical & Safety", type: "mcq",
    question: "Under ASPA, 'protected animals' include all living vertebrates plus which invertebrate group?",
    options: ["Insects", "Cephalopods (e.g. octopus, squid)", "Worms", "Crustaceans in general"],
    answer: 1,
    explanation: "Cephalopods are protected; most other invertebrates are widely used but not regulated/reported under ASPA." },
  { id: "mcq-b6-8", topic: "B6 · Preclinical & Safety", type: "mcq",
    question: "Which licence authorises a specific programme of scientific work ('the what')?",
    options: ["Establishment licence", "Project licence", "Personal licence", "Product licence"],
    answer: 1,
    explanation: "Establishment = the premises (where); project = the programme of work (what); personal = the individual carrying out procedures (who)." },
  { id: "mcq-b6-9", topic: "B6 · Preclinical & Safety", type: "mcq",
    question: "Hazard is best defined as:",
    options: ["The likelihood of harm under specific exposure", "The intrinsic potential of a substance to cause harm", "The dose that kills 50% of animals", "The therapeutic ratio"],
    answer: 1,
    explanation: "Risk is the likelihood of harm under defined conditions of exposure; a highly hazardous substance can carry low risk if exposure is controlled." },
  { id: "mcq-b6-10", topic: "B6 · Preclinical & Safety", type: "mcq",
    question: "In the fixed-dose procedure (OECD TG 420, an LD50 alternative), drug is given at which fixed dose levels?",
    options: ["1, 10, 100, 1000 mg/kg", "5, 50, 500, 2000 mg/kg", "2, 20, 200 mg/kg", "10 and 100 mg/kg only"],
    answer: 1,
    explanation: "Animals are observed over 14 days for 'evident toxicity' using fewer animals than the LD50 and avoiding death as the endpoint." },
  { id: "mcq-b6-11", topic: "B6 · Preclinical & Safety", type: "mcq",
    question: "The long-term rodent carcinogenicity bioassay typically runs for:",
    options: ["1 month", "3 months", "18 months (mice) / 24 months (rats)", "5 years"],
    answer: 2,
    explanation: "Animals are dosed daily with full tissue analysis at termination; substances that induce tumours are presumed human carcinogens until proven otherwise." },
  { id: "mcq-b6-12", topic: "B6 · Preclinical & Safety", type: "mcq",
    question: "Regulatory reproductive-toxicity testing requires studies in:",
    options: ["One rodent species only", "One rodent and one non-rodent species (e.g. rabbit)", "Primates only", "No animals"],
    answer: 1,
    explanation: "Thalidomide (teratogenic in rabbits/primates but not rodents) drove the two-species requirement and attention to chirality." },
  { id: "mcq-b6-13", topic: "B6 · Preclinical & Safety", type: "mcq",
    question: "The S9 fraction is added in the AMES test in order to:",
    options: ["Kill the bacteria", "Provide histidine", "Mimic mammalian metabolic activation", "Count the colonies"],
    answer: 2,
    explanation: "±S9 distinguishes mutagenicity of the parent compound from that of its metabolites." },

  // ---- B7 (extended) ----
  { id: "mcq-b7-6", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "Which route gives the fastest onset of action AND 100% bioavailability?",
    options: ["Oral", "Intravenous", "Transdermal", "Rectal"],
    answer: 1,
    explanation: "IV delivers drug directly to the circulation with onset in seconds — used in emergencies." },
  { id: "mcq-b7-7", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "Transdermal patches (e.g. fentanyl, GTN, nicotine, HRT) are advantageous partly because they:",
    options: ["Are absorbed in the stomach", "Bypass first-pass metabolism and give slow, sustained delivery", "Act within seconds", "Need no skin permeability"],
    answer: 1,
    explanation: "They provide sustained systemic delivery while avoiding presystemic (first-pass) metabolism." },
  { id: "mcq-b7-8", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "Which ranking of dissolution rate (fastest → slowest) for oral forms is correct?",
    options: ["Tablets > capsules > powders > solutions", "Solutions > suspensions > powders > capsules > tablets", "Capsules > tablets > solutions", "All are equal"],
    answer: 1,
    explanation: "Bioavailability generally follows the same order when dissolution is the rate-limiting step." },
  { id: "mcq-b7-9", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "The role of a disintegrant in a tablet is to:",
    options: ["Add bulk volume", "Break the tablet into fragments to aid dissolution", "Colour the tablet", "Lubricate the press"],
    answer: 1,
    explanation: "Disintegration → granules/particles → dissolution → absorption; fillers add bulk, binders give strength, lubricants reduce friction." },
  { id: "mcq-b7-10", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "In an osmotic-pump modified-release tablet, drug release is driven by:",
    options: ["Gastric acid", "Water entering an osmotic core and pushing drug out through a small laser-drilled orifice", "Enzymatic digestion of the shell", "Body temperature"],
    answer: 1,
    explanation: "A rate-controlling membrane plus an osmotic core gives near-constant (zero-order-like) release." },
  { id: "mcq-b7-11", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "A Phase 0 ('early phase 1') microdosing study typically uses:",
    options: ["Thousands of patients", "~10 volunteers and a sub-therapeutic microdose to check human PK", "Healthy volunteers at toxic doses", "No humans at all"],
    answer: 1,
    explanation: "It is optional and confirms the drug behaves in humans as predicted (e.g. oral bioavailability, half-life) before fuller trials." },
  { id: "mcq-b7-12", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "Which clinical study design gives every subject all treatments in a randomised order, acting as their own control?",
    options: ["Parallel-group", "Crossover", "Cohort", "Case-control"],
    answer: 1,
    explanation: "Crossover designs need fewer subjects but are limited by carry-over, order effects and drop-out." },
  { id: "mcq-b7-13", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "A cohort study is best described as:",
    options: ["A snapshot at one time point", "A longitudinal study following a group sharing a characteristic over time", "Random allocation to treatment groups", "A backward-looking records review"],
    answer: 1,
    explanation: "Cross-sectional = a single-time-point snapshot; retrospective = backward-looking; cohort = forward-looking follow-up of a defined group." },
  { id: "mcq-b7-14", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "In a triple-blind trial, who is unaware of the treatment allocation?",
    options: ["The subject only", "The subject and the investigator", "The subject, the investigator AND the data analyst", "Nobody"],
    answer: 2,
    explanation: "Blinding reduces conscious/unconscious bias in subjects' responses, investigators' assessments and data analysis." },
  { id: "mcq-b7-15", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "A statistical significance threshold of P<0.05 means:",
    options: ["The effect is certainly real", "There is about a 5% chance of a false-positive result", "Statistical power is 5%", "The sample was too small"],
    answer: 1,
    explanation: "A P<0.05 result can still arise when there is no true difference (a false positive); power concerns the risk of false negatives." },
  { id: "mcq-b7-16", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "Before first administration to humans, the starting dose is usually set as a fraction of the:",
    options: ["LD50", "NOEL (no observable effect level) or MABEL", "Cmax", "Therapeutic index"],
    answer: 1,
    explanation: "Derived from the most sensitive species, then escalated logarithmically or by doubling in ~4–8 subjects until an adverse event or a pharmacological plasma level is reached." },
  { id: "mcq-b7-17", topic: "B7 · Pharmaceutical Dev & Clinical Evaluation", type: "mcq",
    question: "In the UK, which body appraises the clinical and cost-effectiveness of a newly approved drug to guide NHS prescribing?",
    options: ["MHRA", "FDA", "NICE", "EMA"],
    answer: 2,
    explanation: "NICE (and the Scottish Medicines Consortium in Scotland) is advisory on value for money; the MHRA grants the marketing authorisation." },

  // ---- B8 (extended) ----
  { id: "mcq-b8-6", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "The three chemical elements of a PROTAC are:",
    options: ["An antibody, an enzyme and a linker", "A target-protein ligand, an E3-ligase ligand and a linker", "Two antibodies and a drug", "A lipid, a sugar and a protein"],
    answer: 1,
    explanation: "This bifunctional molecule bridges the target protein and an E3 ubiquitin ligase, driving ubiquitination and proteasomal degradation." },
  { id: "mcq-b8-7", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "Because PROTACs act catalytically, their DC50 (50% degradation concentration) can be:",
    options: ["Higher than KD", "More than 100-fold lower than KD", "Equal to KD", "Undefined"],
    answer: 1,
    explanation: "PROTACs are recycled within the cell, so they act at sub-stoichiometric concentrations — allowing low doses." },
  { id: "mcq-b8-8", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "A current limitation of PROTAC design is that:",
    options: ["No human E3 ligases are known", "Only ~4 of the >600 human E3 ligases have so far been exploited", "They cannot degrade proteins", "They require no linker"],
    answer: 1,
    explanation: "Other challenges include large size (breaking Lipinski's rules), poor membrane permeability, difficult PK/screening, and the hook effect." },
  { id: "mcq-b8-9", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "PROTAC linkers are most commonly made from:",
    options: ["DNA", "Polyethylene glycol (PEG) chains", "Cholesterol", "Cellulose"],
    answer: 1,
    explanation: "PEG provides polarity and flexibility; linker length and attachment point are critical to ternary-complex geometry." },
  { id: "mcq-b8-10", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "How does a 'molecular glue' differ from a PROTAC?",
    options: ["It is bifunctional with a linker", "It is a single-component molecule (not bifunctional) that promotes target–E3 association", "It inhibits the proteasome", "It is a monoclonal antibody"],
    answer: 1,
    explanation: "PROTACs are bifunctional (two warheads joined by a linker); molecular glues are single small molecules that induce protein–protein association." },
  { id: "mcq-b8-11", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "A biologic is defined as:",
    options: ["Any small synthetic molecule", "Any product derived from or produced by a living organism", "Any orally administered drug", "Any drug under 500 Da"],
    answer: 1,
    explanation: "Examples include monoclonal antibodies, recombinant proteins and vaccines." },
  { id: "mcq-b8-12", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "In a monoclonal antibody, the antigen-binding region confers specificity while the Fc region mediates:",
    options: ["Solubility", "Biological/effector activity (e.g. ADCC) via Fc receptors", "Oral absorption", "Renal excretion"],
    answer: 1,
    explanation: "Fc engineering tunes effector functions (ADCC/phagocytosis, glycosylation) and FcRn-mediated half-life." },
  { id: "mcq-b8-13", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "Affinity maturation of a therapeutic antibody typically aims to improve binding affinity from roughly:",
    options: ["0.1–10 nM down to picomolar", "10–100 nM into the 0.1–10 nM range", "µM to mM", "mM to M"],
    answer: 1,
    explanation: "It is applied to antibody leads selected from a naïve human library using a display technology." },
  { id: "mcq-b8-14", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "The pharmacokinetics of monoclonal antibodies differ from small molecules in that mAbs are:",
    options: ["Orally bioavailable", "Eliminated mainly by CYP450", "Not orally bioavailable, distribute via the lymphatics, and are cleared by proteolysis with long (~3–4 week) half-lives", "Rapidly renally excreted as intact protein"],
    answer: 2,
    explanation: "They are given parenterally; FcRn recycling gives long half-lives, and immunogenicity (anti-drug antibodies) is the main safety concern." },
  { id: "mcq-b8-15", topic: "B8 · 21st-Century Approaches", type: "mcq",
    question: "Which AI example is correctly matched?",
    options: ["AlphaFold – designs clinical trials", "DSP-1181 (Exscientia) – first AI-designed drug to enter trials", "Insilico Medicine – predicts protein folding", "Baricitinib – a PROTAC"],
    answer: 1,
    explanation: "AlphaFold predicts protein structure; Insilico Medicine used generative AI (GANs) to design a DDR1 inhibitor; baricitinib was AI-repurposed for COVID-19 by BenevolentAI." },
];

if (typeof window !== "undefined") {
  window.TOPICS = TOPICS;
  window.BLOCKS = BLOCKS;
  window.MCQ_BANK = MCQ_BANK;
}
